[
    {
        "id": 0,
        "nombreComun": "Espinillo",
        "nombreCientifico": "Acacia Caven",
        "tipo": "Árbol",
        "habitatNatural": ["Monte ribereño"],
        "distribucion": ["Brasil", "Chile", "Paraguay", "Uruguay"],
        "floracion": true,
        "estacion": ["Primavera"],
        "descripcion": "Árbol de 2-5 m de altura, de copa ancha con espinas largas, blanquecinas, rectas y germinadas. Hojas pequeñas, flores amarillo-doradas. Su fruto es una legumbre gruesa, cilíndrica, negra. Semillas verdosas.",
        "imagen": "",
        "carrusel": []
    },
    {
        "id": 1,
        "nombreComun": "Pata de Vaca",
        "nombreCientifico": "Bahuinia Forficata",
        "tipo": "Árbol",
        "habitatNatural": ["Monte ribereño"],
        "distribucion": ["Brasil", "Paraguay", "Uruguay"],
        "floracion": true,
        "estacion": ["Verano", "Otoño"],
        "descripcion": "Árbol de 8 a 10 m de altura, con ramas flexuosas, follaje denso. Hojas simples, alternas, de 4 a 15cm de longitud. Flores blancas, grandes de 8 a 13 cm de diámetro, solitarias o en racimos. Su fruto es una legumbre aplanada con semillas ovales, planas de color negro.",
        "imagen": "",
        "carrusel": []
    },
    {
        "id": 2,
        "nombreComun": "Ceibo",
        "nombreCientifico": "Erythrina Crista-galli",
        "tipo": "Árbol",
        "habitatNatural": ["Monte ribereño", "Pajonales", "Ceibales"],
        "distribucion": ["Brasil", "Paraguay", "Uruguay", "Argentina"],
        "floracion": true,
        "estacion": ["Verano", "Primavera"],
        "descripcion": "Árbol de 4 a 10 m de altura, de madera blanda. Tronco de hasta 1 m de diámetro en la base, corteza resquebrajada, persistente. Ramas arqueadas con aguijones recurvos. Hojas caducas de 3 a 11 cm de longitud. Flores rojas en racimos. su fruto es una legumbre de 10 a 20 cm de longitud castaño oscuro. Sus semillas son color castaña",
        "imagen": "",
        "carrusel": []
    },
    {
        "id": 3,
        "nombreComun": "Lapacho Rosado",
        "nombreCientifico": "Handroanthus heptaphyllus",
        "tipo": "Árbol",
        "habitatNatural": ["Monte ribereño"],
        "distribucion": ["Brasil", "Paraguay", "Uruguay", "Argentina"],
        "floracion": true,
        "estacion": ["Primavera"],
        "descripcion": "Árbol de hasta 30 metros de altura. Puede llegar a los 80 cm de diámetro en el tronco. Flores rosadas grandes, de forma tubular. El fruto es una cápsula cilíndrica y estrecha, contiene numerosas semillas",
        "imagen": "",
        "carrusel": []
    },
    {
        "id": 4,
        "nombreComun": "Ibirapitá",
        "nombreCientifico": "Peltophorum dubium",
        "tipo": "Árbol",
        "habitatNatural": ["Monte ribereño"],
        "distribucion": ["América Subtropical"],
        "floracion": true,
        "estacion": ["Verano", "Otoño"],
        "descripcion": "Árbol con corteza rugosa color gris castaño, follaje verde oscuro brillante, caduco. Sus flores son de 2 cm de diámetro. Su fruto es una lagumbre chata color castaño. Sus semillas son cilíndricas.",
        "imagen": "",
        "carrusel": []
    },
    {
        "id": 5,
        "nombreComun": "Tasi",
        "nombreCientifico": "Arauija sericifera",
        "tipo": "Trepadora",
        "habitatNatural": ["Monte"],
        "distribucion": ["América del Sur"],
        "floracion": true,
        "estacion": ["Verano"],
        "descripcion": "Trepadora de rápido crecimiento, puede cubrir el tronco de un árbol en dos o tres años. Tiene flores blancas, pequeñas y perfumadas. Fuera de América del Sur es una especie invasora.",
        "imagen": "",
        "carrusel": []
    },
    {
        "id": 6,
        "nombreComun": "Mburucuyá",
        "nombreCientifico": "Passiflora coemulea",
        "tipo": "Trepadora",
        "habitatNatural": ["Monte"],
        "distribucion": ["Argentina", "Brasil", "Uruguay"],
        "floracion": true,
        "estacion": ["Verano"],
        "descripcion": "Trepadora perenne, indígena, que comúnmente vive trepada a árboles y arbustos de nuestros Montes. Planta de tallos delgados y muy ramificados. Flores vistosas de 6 a 10 cm de diámetro. Su fruto es un Bayo globoso de 4 a 5 cm de largo, anaranjado o rojizo, comestible.",
        "imagen": "",
        "carrusel": []
    },
    {
        "id": 7,
        "nombreComun": "Camalotillo",
        "nombreCientifico": "Hydrocleys nymphoides",
        "tipo": "Trepadora",
        "habitatNatural": ["Monte"],
        "distribucion": ["Argentina", "Brasil", "Uruguay"],
        "floracion": true,
        "estacion": ["Verano"],
        "descripcion": "Trepadora perenne, indígena, que comúnmente vive trepada a árboles y arbustos de nuestros Montes. Planta de tallos delgados y muy ramificados. Flores vistosas de 6 a 10 cm de diámetro. Su fruto es un Bayo globoso de 4 a 5 cm de largo, anaranjado o rojizo, comestible.",
        "imagen": "",
        "carrusel": []
    },
    {
        "id": 8,
        "nombreComun": "Hibisco de agua",
        "nombreCientifico": "Hibiscus striatus",
        "tipo": "Arbusto palustre",
        "habitatNatural": ["Zonas inundables", "Pajonales", "Costas de arroyos", "Cañadas"],
        "distribucion": ["Argentina", "Brasil", "Paraguay", "Uruguay"],
        "floracion": true,
        "estacion": ["Primavera", "Verano"],
        "descripcion": "Arbusto de 1 a 2,5 m de altura. Hojas simples, ovadas. Sus flores son rosadas con nervaduras más oscuras, solitarias. Sus semillas son negras, cubiertas de pelos ásperos.",
        "imagen": ["Hibiscis1", "Hibiscus2", "Hibiscus3", "Hibiscus4"],
        "carrusel": []
    },
    {
        "id": 9,
        "nombreComun": "Rama negra",
        "nombreCientifico": "Senna Corymbosa",
        "tipo": "Planta palustre",
        "habitatNatural": ["Bosque ribereño", "Bañados"],
        "distribucion": ["Argentina", "Brasil", "Paraguay", "Uruguay"],
        "floracion": true,
        "estacion": ["Verano", "Otoño"],
        "descripcion": "Arbusto de 1 a 4 m de altura, con ramas apoyantes, cilíndricas y color rojo-negruzco con la edad. Sus flores son amarillas, vistosas, de 2 cm de diámetro dispuestas en racimos. Fruto con forma de legumbre cilíndrica.",
        "imagen": [""],
        "carrusel": []
    },
    {
        "id": 9,
        "nombreComun": "Pitanga",
        "nombreCientifico": "Eugenia uniflora",
        "tipo": "Árbol fruto comestible",
        "habitatNatural": ["Montes ribereños"],
        "distribucion": ["Argentina", "Brasil", "Paraguay", "Uruguay"],
        "floracion": true,
        "estacion": ["Primavera"],
        "descripcion": "Árbol, siempre verde, de 3 a 12 m de altura. Sus hojas son simples, verde oscuras, lustrosas en el haz y pálidas en el envés. Sus hojas son blancas, fragantes y pequeñas. El fruto es una baya globosa, anaranjada a roja. Su semilla es redonda, castaña.",
        "imagen": ["Pitanga1", "Pitanga2", "Pitanga3", "Pitanga4"],
        "carrusel": []
    },
    {
        "id": 10,
        "nombreComun": "Guayabo del país",
        "nombreCientifico": "Feijoa sellowiana",
        "tipo": "Árbol fruto comestible",
        "habitatNatural": ["Zona de quebradas"],
        "distribucion": ["Argentina", "Chile", "Perú", "Uruguay"],
        "floracion": true,
        "estacion": ["Primavera"],
        "descripcion": "Árbol pequeño que oscila entre 1 a 4 metros de altura. Sus hojas son simples, lúcidas en el haz y blanquecinas en el envés. Flores solitarias de cuatro pétalos",
        "imagen": ["GuayaboDeldistribucion1", "GuayaboDeldistribucion2", "GuayaboDeldistribucion3", "GuayaboDeldistribucion4"],
        "carrusel": []
    },
    {
        "id": 11,
        "nombreComun": "Ubajay",
        "nombreCientifico": "Eugenia myrcianthes",
        "tipo": "Árbol fruto comestible",
        "habitatNatural": ["Montes", "Terrenos arenosos"],
        "distribucion": ["Argentina", "Brasil", "Paraguay", "Uruguay"],
        "floracion": true,
        "estacion": ["Primavera"],
        "descripcion": "Árbol de hasta 10 m de altura, muy ramificado de copa golosa. Hojas simples de 3 a 6 cm de largo. Sus flores son blancas. Los frutos son amarillo-anaranjado con una semilla globosa marrón.",
        "imagen": ["Ubajay1", "Ubajay2", "Ubajay3", "Ubajay4"],
        "carrusel": []
    },
    {
        "id": 12,
        "nombreComun": "Guaviyu",
        "nombreCientifico": "Myrcianthes pungens",
        "tipo": "Árbol fruto comestible",
        "habitatNatural": ["Islas", "Montes ribereños"],
        "distribucion": ["Brasil", "Paraguay", "Uruguay"],
        "floracion": true,
        "estacion": ["Primavera"],
        "descripcion": "Árbol de entre 5 y 12 metros de altura, con copa amplia y corteza maculada. Sus flores son blancas.",
        "imagen": ["Guaviyu1", "Guaviyu2", "Guaviyu3", "Guaviyu4"],
        "carrusel": []
    },
    {
        "id": 13,
        "nombreComun": "Cedrón del monte",
        "nombreCientifico": "Aloysia gratissima",
        "tipo": "Arbusto",
        "habitatNatural": ["Sierras"],
        "distribucion": ["América del Sur"],
        "floracion": true,
        "estacion": ["Primavera", "Verano"],
        "descripcion": "Arbusto aromático de hasta 3 metros de altura, ramoso, con ramas agudo espinosas. Sus flores son blancas, pequeñas, fragantes y dispuestas en racimos.",
        "imagen": ["CedronDelMonte1", "CedronDelMonte2", "CedronDelMonte3", "CedronDelMonte4"],
        "carrusel": []
    },
    {
        "id": 14,
        "nombreComun": "Pindó",
        "nombreCientifico": "Syagrus romanzoffiana",
        "tipo": "Palmera",
        "habitatNatural": ["Bosques"],
        "distribucion": ["Argentina", "Brasil", "Paraguay", "Uruguay"],
        "floracion": true,
        "estacion": ["Primavera", "Verano"],
        "descripcion": "Palmera arbórea, monoica, de unos 10 a 25 m de altura. Sus hojas son de 2 a 5 m. Sus flores son de un color lila-crema, protegidas por una espata leñosa. Su fruto, comestible, es color anaranjado.",
        "imagen": ["Pindo1", "Pindo2", "Pindo3", "Pindo4"],
        "carrusel": []
    },
    {
        "id": 15,
        "nombreComun": "Espina amarilla",
        "nombreCientifico": "Berberis laurina",
        "tipo": "Arbusto",
        "habitatNatural": ["Monte", "Cerros", "Sierras"],
        "distribucion": ["Argentina", "Brasil", "Uruguay"],
        "floracion": true,
        "estacion": ["Invierno", "Primavera"],
        "descripcion": "Arbusto de poca altura, con hojas simples, alternas y espinas trífidas, una por nudo. El interior de las ramas y raíces es amarillo intenso. Sus flores son verdes amarillentas en racimos colgantes.",
        "imagen": ["EspinaAmarilla1", "EspinaAmarilla2", "EspinaAmarilla3", "EspinaAmarilla4"],
        "carrusel": []
    },
    {
        "id": 16,
        "nombreComun": "Yatay",
        "nombreCientifico": "Butia yatay",
        "tipo": "Palmera",
        "habitatNatural": ["Bosques ribereños", "Campos arenosos"],
        "distribucion": ["Argentina", "Uruguay"],
        "floracion": true,
        "estacion": ["Primavera", "Verano"],
        "descripcion": "Palmera de 10 a 20 m de altura. Hojas de hasta 2 m de longitud. Sus flores son amarillentas. Su fruto es de color amarillento anaranjado a rojizo, ovoide o elipsoide.",
        "imagen": ["Yatay1", "Yatay2", "Yatay3", "Yatay4"],
        "carrusel": []
    },
    {
        "id": 17,
        "nombreComun": "Mimosa",
        "nombreCientifico": "Mimosa uraguensis",
        "tipo": "Arbusto",
        "habitatNatural": ["Ribera del Río Uruguay"],
        "distribucion": ["Argentina", "Uruguay"],
        "floracion": true,
        "estacion": ["Primavera", "Verano"],
        "descripcion": "Arbusto, ramoso, de 1 a 3 m de altura. Ramitas rojizas, lisas, con aguijones dispersos, rectos. Sus flores son rosadas. Su fruto es de color oscuro.",
        "imagen": ["Mimosa1", "Mimosa2", "Mimosa3", "Mimosa4"],
        "carrusel": []
    }
]
    
